name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Stop MySql
        run: sudo service mysql stop
      - name: Run docker-compose
        run: docker-compose up -d
      - name: build app
        run: cd app && go build main.go
